#!/usr/bin/env node
/**
 * Excel / CSV → Fable deck HTML placeholders + presentation.json
 *
 * Usage:
 *   node scripts/csv-to-deck.mjs --excel path/to/file.xlsx --write-json
 *   node scripts/csv-to-deck.mjs --master data/templates/master.csv
 *   npm run csv-to-deck -- --excel ./RFP.xlsx
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import XLSX from "xlsx";
import { fillPlaceholderHtml, parseWorkbook } from "../js/import-workbook.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const NAMES = {
  AT: "Austria",
  PL: "Poland",
  RO: "Romania",
  CZ: "Czechia",
  SK: "Slovakia",
  HU: "Hungary",
  HR: "Croatia",
  RS: "Serbia",
};

function parseArgs(argv) {
  const out = {
    excel: null,
    master: path.join(ROOT, "data", "templates", "master.csv"),
    html: path.join(ROOT, "deck-shell.html"),
    outHtml: path.join(ROOT, "Million-Engine.html"),
    writeJson: false,
    rate: 0.005,
    dryRun: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--excel") out.excel = path.resolve(argv[++i]);
    else if (a === "--master") out.master = path.resolve(argv[++i]);
    else if (a === "--html") out.html = path.resolve(argv[++i]);
    else if (a === "--out") out.outHtml = path.resolve(argv[++i]);
    else if (a === "--rate") out.rate = Number(argv[++i]);
    else if (a === "--write-json") out.writeJson = true;
    else if (a === "--dry-run") out.dryRun = true;
    else throw new Error(`Unknown flag: ${a}`);
  }
  return out;
}

function parseMasterCsvAsWorkbook(filePath) {
  const text = fs.readFileSync(filePath, "utf8");
  const lines = text.trim().split(/\r?\n/).filter(Boolean);
  const header = lines[0].toLowerCase();
  let csvText = text;
  if (header.includes("country") && header.includes("target") && !header.includes("countries")) {
    const body = lines.slice(1).map((line) => {
      const [code, target, ms] = line.split(",");
      return `${NAMES[code] || code},${target},${ms}`;
    });
    csvText = ["Countries,Target cards allocation (27'F),Market Share", ...body].join("\n");
  }
  return XLSX.read(csvText, { type: "string", FS: "," });
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  let parsed;

  if (args.excel) {
    if (!fs.existsSync(args.excel)) throw new Error(`Excel not found: ${args.excel}`);
    const wb = XLSX.readFile(args.excel);
    parsed = parseWorkbook(wb, XLSX, { rate: args.rate });
  } else if (fs.existsSync(path.join(ROOT, "masterexcel.xlsx")) && !process.argv.includes("--master")) {
    args.excel = path.join(ROOT, "masterexcel.xlsx");
    const wb = XLSX.readFile(args.excel);
    parsed = parseWorkbook(wb, XLSX, { rate: args.rate });
  } else {
    if (!fs.existsSync(args.master)) throw new Error(`Master CSV not found: ${args.master}`);
    const wb = parseMasterCsvAsWorkbook(args.master);
    parsed = parseWorkbook(wb, XLSX, { rate: args.rate });
  }

  console.log(
    `${args.excel ? "Excel" : "CSV"} sheet “${parsed.sheet}” · ${parsed.rows.length} countries · ${Object.keys(parsed.tags).length} tags`
  );

  if (!fs.existsSync(args.html)) throw new Error(`HTML template not found: ${args.html}`);
  const raw = fs.readFileSync(args.html, "utf8");
  const { html, hits } = fillPlaceholderHtml(raw, parsed.tags);
  console.log(`Replaced ${hits} placeholder occurrence(s)`);

  if (args.dryRun) {
    console.log("(dry-run — no files written)");
    return;
  }

  fs.writeFileSync(args.outHtml, html, "utf8");
  console.log(`Wrote ${path.relative(ROOT, args.outHtml)}`);

  if (args.writeJson) {
    const jsonPath = path.join(ROOT, "data", "presentation.json");
    const jsPath = path.join(ROOT, "js", "data", "presentation.js");
    fs.writeFileSync(jsonPath, `${JSON.stringify(parsed.presentation, null, 2)}\n`, "utf8");
    fs.writeFileSync(
      jsPath,
      `/** Generated by csv-to-deck.mjs */\nexport const PRESENTATION_DATA = ${JSON.stringify(
        parsed.presentation,
        null,
        2
      )};\n`,
      "utf8"
    );
    console.log(`Wrote ${path.relative(ROOT, jsonPath)}`);
  }
}

main();
